config/routes.rb
Rails.application.routes.draw do
  get "links/historia", to: "links#historia", as: "historia_links"
  root "pages#index"
  get "pages/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def historia
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lens2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag 'fontawesome-all.min', 'main', 'noscript', media: 'all' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!-- <body class="is-preload-0 is-preload-1 is-preload-2"> -->
  <body>
    <!-- Main -->
    <div id="main">
      <!-- Header -->
      <header id="header">
        <h1><%= link_to 'Tattoo', root_path %></h1>
        <h2><%= link_to 'Historia del Tatuaje', historia_links_path %></h2>
        <p>Sitio responsivo generado en el framework <a href="https://rubyonrails.org/">Rails 7.2.1</a></p>
        <ul class="icons">
          <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
          <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
        </ul>
      </header>

      <%= yield %>

      <!-- Footer -->
      <footer id="footer">
        <ul class="copyright">
          <li>&copy; Untitled.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a>.</li>
        </ul>
      </footer>
    </div>

    <!-- Scripts -->
      <%= javascript_include_tag 'jquery.min' %>
      <%= javascript_include_tag 'browser.min' %>
      <%= javascript_include_tag 'breakpoints.min' %>
      <%= javascript_include_tag 'main' %>

  </body>
</html>

app/views/links/historia.html.erb
<p>
    El tatuaje, una forma de expresión milenaria, ha evolucionado desde un ritual tribal a un arte global. Desde sus orígenes como lenguaje visual en culturas antiguas, donde simbolizaba identidad, estatus y creencias, hasta su auge contemporáneo como expresión individual y artística, el tatuaje ha dejado una huella imborrable en la historia humana.
    Los diseños, que van desde símbolos ancestrales hasta obras de arte intrincadas, han trascendido fronteras culturales y se han convertido en una forma de conectar con nuestras raíces, conmemorar momentos importantes o simplemente expresar nuestra personalidad. La evolución tecnológica ha hecho que el tatuaje sea más seguro y accesible, permitiendo a los artistas crear diseños cada vez más detallados y realistas.
    Sin embargo, la percepción del tatuaje varía ampliamente entre culturas y sociedades. Mientras en algunas es un símbolo de respeto y conexión espiritual, en otras puede estar asociado con estigmas sociales. A pesar de estas diferencias, el tatuaje se ha consolidado como una forma de arte que trasciende barreras y une a personas de diversos orígenes en la búsqueda de una expresión auténtica y personal.
</p>

app/views/pages/index.html.erb
<!-- Thumbnail -->
<section id="thumbnails">
    <% (1..12).each do |i| %>
        <article>
            <a class="thumbnail" href="<%= asset_path("fulls/#{i.to_s.rjust(2, '0')}.jpg") %>" data-position="left center">
                <img src="<%= asset_path("thumbs/#{i.to_s.rjust(2, '0')}.jpg") %>" alt="" />
            </a>
            <h2><%= "Thumbnail Title #{i}" %></h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </article>
    <% end %>
</section>